sudo: required
dist: bionic
language: cpp
compiler:
  - gcc
  - clang
notifications:
  email: false
addons:
  apt:
    sources:
    packages:
    - gcc-8
    - g++-8
    - cmake
script: mkdir build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=Release && make -r -j `nproc`
