sudo: required
dist: focal
language: cpp
notifications:
  email: false
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8','ninja-build']
      env: CC=gcc-8 CXX=g++-8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-9','ninja-build']
      env: CC=gcc-9 CXX=g++-9
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['ninja-build']
      env: CC=clang CXX=clang++
script: bash ./scripts/build-linux-cpu.sh
